version: '3.3'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: elx_dev
    ports:
      - 5432:5432

  message-queue:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on:
      - db